[functions]
  directory = "netlify/functions"

[[edge_functions]]
  path = "/*"
  function = "auth"

[[redirects]]
  from = "/api/jobs/*"
  to = "/.netlify/functions/jobs/:splat"
  status = 200

[[redirects]]
  from = "/api/jobs"
  to = "/.netlify/functions/jobs"
  status = 200

[[redirects]]
  from = "/api/calendar/*"
  to = "/.netlify/functions/google-calendar/:splat"
  status = 200

[[redirects]]
  from = "/api/calendar"
  to = "/.netlify/functions/google-calendar"
  status = 200

[[redirects]]
  from = "/api/stats"
  to = "/.netlify/functions/stats"
  status = 200
